spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to 'validate' or 'none' for production
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: Asia/Kolkata
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always  # set to 'never' if you donâ€™t want schema/data auto initialization

server:
  port: 8080

app:
  jwt:
    secret: "uB0sjhF5K9w7RnA3KkduGxFq2TQp0Bv6fDe9JbP8zHc="
    expiration-ms: 3600000  # 1 hour in ms
